# Site
#repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Debora Vittone
title: Educatrice e futura Pedagogista
email: deb.vittone@gmail.com
website: (poi mi dirai il nome del sito che desideri! Fa parte del regalo :-))

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: deboravittone
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: deboravittone
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Su di me
about_profile_image: images/debora.jpeg
about_content: | # this will include new lines to allow paragraphs
  Ciao a tutti! Il mio nome è Debora Vittone e... (completa tu)

content:
  - title: I miei progetti # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Perché ho voluto creare questo sito
        link: (qui potrai mettere i link ai tuoi futuri progetti)
        # link_text: Project Website
        additional_links:
          - title:  (titolo del progetto)
            icon: fab fa-instagram
            url: (qui puoi mettere ancora un altro link)
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Ecco una piccola spiegazione.
        description: | # this will include new lines to allow paragraphs
          Ho pensato molto a che regalo farti! Mi piaceva l'idea di provare a fare qualcosa con le mie mani, ad esempio un disegno, una scultura, anche soltanto un dolce, ma la mia abilità artigianale ha a che fare solo con l'informatica, quindi ecco qui!! :-). 
          
          Ho pensato che che questa pagina web potrebbe servire a 2 scopi: da un lato familiarizzare un po' con una tecnologia per fare siti. Dall'altro, e soprattuto, per darti l'occasione di cominciare a costruire un piccolo spazio virtuale, che possa essere un punto di riferimento per te e soprattutto per gli altri. Questo non deve essere per forza un sito in cui scrivi tutto, ma potrebbe essere un recipiente in cui inserisci semplicemente un riferimento a progetti universitari e professionali di cui ti occupi e di cui ti occuperai!

          Credo che possa essere davvero uno dei tanti modi per mostrare al mondo quello che sai!

          (io comunque, sulla parte più Web, posso sempre darti una mano!)

          ps. proprio come in negozio, il sito si può cambiare! Puoi scegliere qui se c'è qualcos'altro che ti piace: https://jekyllthemes.dev/.

  - title: Esperienza # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Stranaidea
        link: https://www.stranaidea.it/
        # link_text: boringcompany.com
        sub_title: Educatrice d'infania
        caption: Settembre 2020 - Oggi
        quote: >
          Quell´idea strana di valorizzare idee semplici.
        description: | # this will include new lines to allow paragraphs
            In Stranaidea mi occupa di una piccola bimba di nome Sofia... (continua tu)

  - title: Formazione # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Università degli Studi di Torino
        caption: 2020 - oggi
        sub_title: Laure Specialistica in Programmazione e gestione dei servizi educativi 
        quote: >
          Con circa 120 sedi dislocate su sette poli principali, una ricerca scientifica di alto livello e una didattica all'avanguardia, l'Università di Torino si colloca come una tra le più prestigiose realtà accademiche nel panorama universitario italiano.
        description: | # this will include new lines to allow paragraphs
          Nel mio corso di studi mi occupo di... (continua tu)

  - title: Qualcosa in più su di me...
    layout: text
    content: | # this will include new lines to allow paragraphs
      Sei una persona curiosa, metodica, scrupolosa e attenta ai dettagli. Sempre alla ricerca di nuove idee e nuovi progetti educativi da esplorare!
      (Io ho scritto che cosa penso di te, ora scrivi tu che cosa pensi di te!!)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
